services:
    moonuserbot:
        image: qbtaumai/moonubcloud:latest-cloud
        container_name: moonuserbot
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - default

networks:
    default:
        external: false
